name: Update README Stats

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add changes
        run: git add README.md
      
      - name: Commit changes
        run: git commit -m "Auto-update README [skip ci]" || exit 0
      
      - name: Pull latest changes from remote
        run: git pull --rebase origin main
      
      - name: Push changes
        run: git push
