name: Update README Stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
     
      - name: Commit & Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update README [skip ci]" || exit 0
          git pull --rebase
          git push
     
