name: Update Profile

on:
  schedule:
    # Runs every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Example: Update date/time in README.md
      - name: Update README
        run: |
          echo "Last auto-update: $(date -u)" > README.md

      - name: Commit & Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update README [skip ci]" || exit 0
          git push
